behaviors:
  CobotAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0002
      learning_rate_schedule: constant 
      batch_size: 1028
      buffer_size: 1000000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: true
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 20
    checkpoint_interval: 250000
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 5000
    threaded: false
    self_play: null
    behavioral_cloning:
      demo_path: "recordingpinkp1.demo"
      strength: 0.9
      steps: 100000